In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv(r"C:\Users\ANURAG DAS\Downloads\customer_churn_raw_dataset.csv",encoding="latin1")
df.info()
df.head()
for i in df.columns:
  print(df[i].value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5040 entries, 0 to 5039
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   5040 non-null   object
 1   age                           4891 non-null   float64
 2   gender                        5040 non-null   object
 3   location                      4940 non-null   object
 4   subscription_type             5040 non-null   object
 5   monthly_fee_usd               5040 non-null   float64
 6   subscription_duration_months  5040 non-null   int64
 7   engagement_score              4840 non-null   float64
 8   box_interactions_per_month    5040 non-null   int64
 9   total_revenue_usd             5040 non-null   object
 10  is_churned                    5040 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 433.2+ KB
customer_id
BOX-4328    2
BOX-4840    2
BOX-3544    2
BOX-4006    2
BOX-5031    2
           ..
BOX-3063    1
BOX-4131    1
BOX-4065    1
BOX-5044    1
BOX-1860    1
Name: count, Length: 5000, dtype: int64
age
 64.0     125
 45.0     120
 62.0     119
 46.0     118
 38.0     118
 52.0     117
 39.0     116
 34.0     115
 54.0     115
 49.0     114
 25.0     112
 43.0     112
 42.0     110
 58.0     109
 50.0     109
 28.0     108
 20.0     108
 53.0     107
 51.0     105
 57.0     105
 21.0     105
 40.0     105
 19.0     104
 56.0     102
 47.0     102
 22.0     102
 36.0     102
 41.0     102
 32.0     102
 29.0     102
 18.0     102
 23.0     101
 61.0     101
 37.0     101
 30.0     100
 26.0     100
 27.0      98
 35.0      98
 55.0      98
 31.0      97
 59.0      94
 44.0      88
 63.0      88
 33.0      83
 60.0      82
 24.0      79
 48.0      73
-1.0       10
 142.0      8
Name: count, dtype: int64
gender
Male          2324
Female        2210
Other          187
M               49
MALE            44
 female         43
FEMALE          39
male            38
F               36
 male           31
female          29
other            4
other            3
Non-Binary       3
Name: count, dtype: int64
location
Urban        2622
Suburban     1392
Rural         736
URBAN          67
urban          47
suburban       28
rural          24
Sub-Urban      24
Name: count, dtype: int64
subscription_type
Standard    2326
Basic       1707
Premium     1007
Name: count, dtype: int64
monthly_fee_usd
29.99    2326
19.99    1707
49.99    1007
Name: count, dtype: int64
subscription_duration_months
48    300
2     285
1     282
3     251
4     226
5     223
7     221
6     207
9     191
12    179
10    174
8     173
11    151
13    143
16    131
15    124
14    113
18    110
21    106
17    105
20    103
19    103
22     91
25     85
23     74
24     73
26     65
31     59
28     58
29     56
30     48
33     47
27     45
38     43
35     41
32     36
37     36
36     33
41     32
34     31
40     30
39     29
42     27
43     24
46     21
44     21
45     18
47     16
Name: count, dtype: int64
engagement_score
10.0    144
6.6     128
6.3     113
5.9     112
7.4     111
       ...
1.4       3
1.9       3
1.6       1
1.5       1
1.2       1
Name: count, Length: 90, dtype: int64
box_interactions_per_month
3     903
4     881
2     793
5     666
1     528
6     433
7     297
0     192
8     178
9      96
10     41
11     16
12      6
13      5
14      3
15      1
16      1
Name: count, dtype: int64
total_revenue_usd
1439.52       133
59.98         128
89.97         120
29.99         113
39.98          99
             ...
119.94 USD      1
779.74 USD      1
$819.59         1
319.84 USD      1
$1049.79        1
Name: count, Length: 278, dtype: int64
is_churned
0    3001
1    2039
Name: count, dtype: int64

In [12]:
df.drop_duplicates(subset=['customer_id'],inplace=True)
df['customer_id'].value_counts()
avg_age=np.mean(df['age'])
df['age']=df['age'].fillna(avg_age)
df['age']=df['age'].astype(int)
df.info()
df.head(5)

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 0 to 5039
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   5000 non-null   object
 1   age                           5000 non-null   int32
 2   gender                        5000 non-null   object
 3   location                      4900 non-null   object
 4   subscription_type             5000 non-null   object
 5   monthly_fee_usd               5000 non-null   float64
 6   subscription_duration_months  5000 non-null   int64
 7   engagement_score              4802 non-null   float64
 8   box_interactions_per_month    5000 non-null   int64
 9   total_revenue_usd             5000 non-null   object
 10  is_churned                    5000 non-null   int64
dtypes: float64(2), int32(1), int64(3), object(5)
memory usage: 449.2+ KB

,customer_id,age,gender,location,subscription_type,monthly_fee_usd,subscription_duration_months,engagement_score,box_interactions_per_month,total_revenue_usd,is_churned
0,BOX-5350,43,Male,Suburban,Basic,19.99,7,10.0,3,139.93,0
1,BOX-4305,43,Female,Suburban,Premium,49.99,10,4.7,5,499.9,1
2,BOX-2736,50,Male,urban,Basic,19.99,10,6.2,7,199.9,0
3,BOX-4050,56,Female,Suburban,Standard,29.99,10,4.6,3,299.9,0
4,BOX-4311,37,Male,Urban,Premium,49.99,6,7.4,2,299.94,0

In [13]:
mod_location=df['location'].mode()[0]
print(mod_location)
df['location']=df['location'].fillna(mod_location)
mean_engagement=np.mean(df['engagement_score'])
df['engagement_score']=df['engagement_score'].fillna(mean_engagement)
df.info()
df.head()

Urban
<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 0 to 5039
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   5000 non-null   object
 1   age                           5000 non-null   int32
 2   gender                        5000 non-null   object
 3   location                      5000 non-null   object
 4   subscription_type             5000 non-null   object
 5   monthly_fee_usd               5000 non-null   float64
 6   subscription_duration_months  5000 non-null   int64
 7   engagement_score              5000 non-null   float64
 8   box_interactions_per_month    5000 non-null   int64
 9   total_revenue_usd             5000 non-null   object
 10  is_churned                    5000 non-null   int64
dtypes: float64(2), int32(1), int64(3), object(5)
memory usage: 449.2+ KB

,customer_id,age,gender,location,subscription_type,monthly_fee_usd,subscription_duration_months,engagement_score,box_interactions_per_month,total_revenue_usd,is_churned
0,BOX-5350,43,Male,Suburban,Basic,19.99,7,10.0,3,139.93,0
1,BOX-4305,43,Female,Suburban,Premium,49.99,10,4.7,5,499.9,1
2,BOX-2736,50,Male,urban,Basic,19.99,10,6.2,7,199.9,0
3,BOX-4050,56,Female,Suburban,Standard,29.99,10,4.6,3,299.9,0
4,BOX-4311,37,Male,Urban,Premium,49.99,6,7.4,2,299.94,0

In [14]:
df['gender']=df['gender'].str.strip().str.title()
mapping={
    'M':'Male',
    'F':'Female',
    'Non-Binary':'Other'
}
df['gender']=df['gender'].replace(mapping)
df['gender'].value_counts()

gender
Male      2468
Female    2340
Other      192
Name: count, dtype: int64

In [15]:
churn_rate=df['is_churned'].mean()*100
print(churn_rate)
type_wise_churn=df.groupby('subscription_type')['is_churned'].mean()*100.
print(type_wise_churn.round(2))
df.to_csv("customer_churn_cleaned.csv", index=False)

40.46
subscription_type
Basic       36.98
Premium     51.50
Standard    38.23
Name: is_churned, dtype: float64